### PR TITLE
Vicmaster Colima

### PR DESCRIPTION
**Pull request by vicmaster**
- Info about Colima, Mexico
- Places to eat tacos

### CODE REVIEW

**Comment by 8geonirt** [comment]
LGTM!

**Comment by vicmaster** [comment]
Hey Guys, could you review my PR and check if it's 👍  to 🚢 ? @8geonirt @githubteacher  @mtucker01752

**Comment by 8geonirt** [comment]
I suggest adding 'Tacos de Humo' to the list 🙈

**Comment by vicmaster** [comment]
Sure thing, I'll with add it

**Comment by markrtucker** [comment]
LGTM - Taco Loco sounds like fun!

**Comment by vicmaster** [comment]
@mtucker01752 tasty and fun! 👍

**Comment by vicmaster** [comment]
@8geonirt I added your suggestion

**Pull request merged**
